# Generated by Django 6.0.5 on 2026-05-21 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petNome', models.CharField(max_length=150)),
                ('medicoNome', models.CharField(max_length=150)),
                ('motivo', models.CharField(max_length=255)),
                ('data', models.CharField(max_length=20)),
                ('hora', models.CharField(max_length=10)),
                ('status', models.CharField(default='agendada', max_length=20)),
                ('prontuario', models.JSONField(blank=True, default=dict, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstoqueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('categoria', models.CharField(default='Medicamentos', max_length=100)),
                ('quantidade', models.IntegerField(default=0)),
                ('limiteMinimo', models.IntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], default='M', max_length=1)),
                ('crmv', models.CharField(max_length=20, unique=True)),
                ('especialidade', models.CharField(default='Clínico Geral', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('telefone', models.CharField(default='Não informado', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('especie', models.CharField(max_length=50)),
                ('raca', models.CharField(default='Sem Raça Definida (SRD)', max_length=100)),
                ('peso', models.CharField(default='--', max_length=10)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='clinica.tutor')),
            ],
        ),
    ]
